<link rel="stylesheet" href="{{asset('assets/website/fonts/stylesheet.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/reset.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/global.css')}}">
<link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<link rel="stylesheet" href="{{asset('assets/website/css/main-alpha.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/main-bravo.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/main-charlie.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/main-delta.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/media-alpha.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/media-bravo.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/media-charlie.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/media-delta.css')}}">
<link rel="stylesheet" href="{{asset('assets/website/css/additional.css')}}">
